### ISSUE TITLE
Model with legitimate `foo` and `foo_id` columns override each other to nil

### ISSUE THREAD

**Issue by sighmin** [thoughtbot/factory_girl#796] opened 2015-07-10 12:25 UTC
Recreate in a fresh rails app:
```sh
$ rails new factory_girl_test && cd factory_girl_test
$ echo "gem 'factory_girl_rails', '~> 4.5.0', group: [:test, :development]" >> Gemfile
$ bundle install
$ rails g model Thing name version_id:integer version:integer
$ rake db:create db:migrate
$ rails c
Loading development environment (Rails 4.2.3)
irb(main):001:0> FactoryGirl.build :thing, version: 4
=> #<Thing id: nil, name: "MyString", version: 4, version_id: nil, created_at: nil, updated_at: nil>
irb(main):002:0> FactoryGirl.build :thing, version_id: 4
=> #<Thing id: nil, name: "MyString", version: nil, version_id: 4, created_at: nil, updated_at: nil>
irb(main):003:0> FactoryGirl.build :thing, version_id: 4, version: 3
=> #<Thing id: nil, name: "MyString", version: nil, version_id: nil, created_at: nil, updated_at: nil>
```

I'm aware of the convention that if version was a model, then `version` and `version_id` attributes have special meaning in factory girl because they represent associations.

Is this something that shouldn't be happening? I don't want to submit a PR if this is not identified as a bug :+1: 

My work around is something like this in the thing factory:

```ruby
# test/factories/things.rb
FactoryGirl.define do
  factory :thing do
    name "MyString"
    version 1
    version_id 1

    # HACK:
    after(:build) do |thing, evaluator|
      thing.version_id ||= evaluator.version_id
      thing.version ||= evaluator.version
    end
  end
end
```

**Comment by sighmin** [comment] 2015-07-10 12:26
Props to @jellymann for his help on this

**Comment by t4deu** [comment] 2015-09-09 11:28
Duplicate with #734

**Comment by joshuaclayton** [comment] 2016-02-07 05:29
@sighmin this is currently not a bug; within FG proper, there's the concept of aliases, and the introduction of foo/foo_id and resolving them was due in part to FG primarily being used for ActiveRecord classes in the beginning. I've been thinking recently about making this behavior opt-in in, since it's potentially confusing, especially when used with non-AR-backed models.

**Closed by joshuaclayton** 2016-02-07 05:29 UTC
