### ISSUE TITLE
Share traits across factories, but not globally.

### ISSUE THREAD

**Issue by MonikaMahanthappa** [thoughtbot/factory_girl#689] opened 2014-08-28 10:32 UTC
Im aware of sharing the traits across factory using FactoryGirl.define global scope. But i do not want to do the same. Why? Because,

1. We have one factory per model in its own file. Now if we keep the shared traits in global scope (outside model factory file) then it is not clear from the code as to which all traits are available on the factory.

2. Can't mimic helpers & modules concept in factory. Like, if there is some task achieved in module and it is included in model then we need specific place to keep module behaviour in one place(not in global scope) probably as `traits/ factory` and include it in other factories.

**Comment by tom-lord** [comment] 2015-07-07 11:05
+1

Perhaps this could be achieved by changing the way that shared factory attributes are mixed-in? This has been discussed before, but rejected due to the "bad idea" of having nested traits: https://github.com/thoughtbot/factory_girl/issues/360

But for example, what if shared attributes are re-named `mixins` instead of `traits`? We could have syntax like this:

```
FactoryGirl.define do
  mixin :shared_foobar
    status 'New'
    association :xyz

    trait :queried do
      queried true
      query_reason 'Dummy Query'
    end
    
    # ....

  end

  factory :big_foobar, mixins: [:shared_foobar] do
     # ...
  end
  factory :small_foobar, mixins: [:shared_foobar] do
     # ...
  end
end

FactoryGirl.build(:big_foobar, :queried)

```

I would find this particularly useful for my current scenario, where I'm dealing with lots of models that use polymorphic relationships.

**Comment by mjbellantoni** [comment] 2015-12-10 17:05
+1

**Comment by joshuaclayton** [comment] 2016-10-07 19:03
Given the complexity and specific nature of this, and new syntax, I don't think this is something FG will support. Closing.

**Closed by joshuaclayton** 2016-10-07 19:03 UTC

**Comment by Startouf** [comment] 2022-10-10 11:17
Hello, after upgrading from factory bot 5 to 6, I have a new error related to this topic where my shared traits no longer seem to recognize my model attributes (but instead interpret them as missing traits)

That is if I have 

```
class User
  include Mongoid::Document

  field :my_attribute
end

FactoryBot.define do
  trait :my_trait do
    my_attribute { "some value" }
  end
end
FactoryBot.define do
  factory :user, class: ::User do
end
```

I get the following error when creating my data

> KeyError:
       Trait not registered: "my_attribute" referenced within "my_trait" definition

In the [update for v6](https://github.com/thoughtbot/factory_bot/releases/tag/v6.0.0), I believe this is referenced as "Removed: support for "abstract" factories with no associated class; use traits instead."

Any idead/guidelines on how to deal with this new behavior @joshuaclayton ?

I'm adding my message as a post in this existing (and closed) issue, would this deserve a bug report or something else ? I'm not quite sure what is the expected behavior here.
