### ISSUE TITLE
 PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type money: "60.94"

### ISSUE THREAD

**Issue by SergeyKutsko** [thoughtbot/factory_girl#803] opened 2015-08-13 18:16 UTC
/home/serg/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/linter.rb:14:in `lint!': The following factories are invalid: (FactoryGirl::InvalidFactoryError)

* transfer - PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type money: "60.94"
: INSERT INTO "transfers" ("aasm_state", "amount", "transfer_type", "bank_account_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id" (ActiveRecord::StatementInvalid)
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/linter.rb:4:in `lint!'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl.rb:59:in `lint'
	from /home/serg/projects/stash-invest-rails/spec/rails_helper.rb:46:in `block (2 levels) in <top (required)>'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:333:in `instance_exec'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:333:in `instance_exec'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:357:in `run'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1559:in `block in run_hooks_with'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1559:in `each'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1559:in `run_hooks_with'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1525:in `with_suite_hooks'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:109:in `block in run_specs'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/reporter.rb:62:in `report'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:108:in `run_specs'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:86:in `run'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/serg/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /home/serg/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from /home/serg/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from /home/serg/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/serg/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by joshuaclayton** [comment] 2016-02-07 05:26
@SergeyKutsko are you still running into this? Looks to be an invalid data type and not something specific to FactoryGirl. I'll close this, but don't hesitate to re-open if the type is correct, you're still running into issues, and you can't reproduce it with just ActiveRecord model interaction.

**Closed by joshuaclayton** 2016-02-07 05:26 UTC
